import {readFileSync} from "node:fs";
import assert from "node:assert/strict";
const root="assets/data/sntf/";
const data=name=>JSON.parse(readFileSync(root+name+".json","utf8"));
const {stations}=data("stations"),{routes}=data("routes"),{trips}=data("trips"),{calendars,exceptions}=data("calendars"),{dates:holidays}=data("holidays");
const source=readFileSync("assets/js/sntf-trains/engine.js","utf8");
const engine=await import("data:text/javascript;base64,"+Buffer.from(source).toString("base64"));
const config={calendars,exceptions,holidays};
const available=engine.eligible(trips);
const drafts=trips.filter(t=>t.data_status==="pending_review");
const verifiedByUser=trips.filter(t=>t.data_status==="source_transcribed");
assert.equal(available.length,14,"Draft journeys must not appear on default boards");
assert.equal(drafts.length,9,"Keep nine editable draft journeys");
assert.equal(verifiedByUser.length,14,"Preserve fourteen transcribed Zeralda–Agha trains");
assert(stations.some(s=>s.id==="rouiba"),"Rouiba station is indexed");
assert(routes.some(r=>r.id==="alger-thenia"&&r.stops.includes("rouiba")),"Rouiba should be visible in eastbound route");
assert(routes.some(r=>r.id==="thenia-alger"&&r.stops.includes("rouiba")),"Rouiba should be visible in westbound route");
const tr1500=available.find(t=>t.train_number==="1500"),tr1502=available.find(t=>t.train_number==="1502");
assert(tr1500&&tr1502);
assert.equal(engine.runsOn(tr1500,"2026-09-24",calendars,exceptions,holidays),true,"1500 should operate on a Thursday");
assert.equal(engine.runsOn(tr1500,"2026-09-25",calendars,exceptions,holidays),false,"1500 should not operate on Friday");
assert.equal(engine.runsOn(tr1502,"2026-09-25",calendars,exceptions,holidays),true,"1502 should operate Friday");
assert.equal(engine.runsOn(tr1500,"2026-09-18",calendars,exceptions,holidays),false,"Image timetable not before effective date");
const fridayOnly=drafts.find(t=>t.service_id==="friday_holiday");
const excludingHoliday=drafts.find(t=>t.service_id==="weekday_not_friday");
assert(fridayOnly&&excludingHoliday);
assert.equal(engine.runsOn(fridayOnly,"2026-09-24",calendars,exceptions,["2026-09-24"]),true,"Holiday-only service should operate on listed holiday");
assert.equal(engine.runsOn(excludingHoliday,"2026-09-24",calendars,exceptions,["2026-09-24"]),false,"Excluding service should not operate on listed holiday");
const beforeDeparture=new Date("2026-09-24T05:20:00Z"); // 06:20 in Algeria.
const fromZeralda=engine.recordsAtStation(available,"zeralda","departure","2026-09-24",config,beforeDeparture);
assert(fromZeralda.some(e=>e.trip.train_number==="1502"&&engine.formatTime(e.stop.departure)==="06:55"),"Upcoming outbound departures should be listed");
const atAgha=engine.recordsAtStation(available,"agha","arrival","2026-09-24",config,beforeDeparture);
assert(atAgha.some(e=>e.trip.train_number==="1500"&&engine.formatTime(e.stop.arrival)==="07:01"),"Arrivals at terminal should be listed");
assert(!engine.recordsAtStation(available,"agha","departure","2026-09-24",config,beforeDeparture).some(e=>e.trip.train_number==="1500"),"No false departure at terminating station");
const mid=engine.recordsAtStation(available,"birtouta","departure","2026-09-24",config,beforeDeparture);
assert(mid.some(e=>e.trip.train_number==="1502"&&e.destination==="agha"&&e.previous==="tessala-el-merdja"),"Intermediate station events must retain direction and previous stop");
const draftsFromRouiba=engine.recordsAtStation(drafts,"rouiba","departure","2026-09-24",config,beforeDeparture);
assert.equal(draftsFromRouiba.length,0,"A draft intermediate stop without time must not appear on departures");
const night=drafts.find(t=>t.route_id==="oran-bechar");
assert(night,"Need one overnight draft for rollover check");
const dawn=new Date("2026-09-24T04:00:00Z"); // 05:00 in Algeria.
const arrivals=engine.recordsAtStation([night],"bechar","arrival","2026-09-24",config,dawn);
assert(arrivals.some(e=>e.serviceDate==="2026-09-23"&&e.remaining===2400),"Yesterday's overnight service arrives this morning");
assert.equal(engine.countdown(3661),"01:01:01");
console.log("DZ Rail board tests PASS: source isolation, two directions, intermediate stops, daily/Friday/holiday rules, 24+ hour rollover and countdown.");
