import {readFileSync} from "node:fs";
import assert from "node:assert/strict";
const root="assets/data/sntf/";
const data=name=>JSON.parse(readFileSync(root+name+".json","utf8"));
const {stations}=data("stations"),{routes}=data("routes"),{trips}=data("trips"),{calendars,exceptions}=data("calendars"),{dates:holidays}=data("holidays");
const source=readFileSync("assets/js/sntf-trains/engine.js","utf8");
const engine=await import("data:text/javascript;base64,"+Buffer.from(source).toString("base64"));
const config={calendars,exceptions,holidays};
const available=engine.eligible(trips);
const drafts=trips.filter(t=>t.data_status==="pending_review");
const verifiedByUser=trips.filter(t=>t.data_status==="source_transcribed");
assert.equal(available.length,131,"131 official image-transcribed journeys are visible; drafts excluded");
assert.equal(drafts.length,9,"Keep nine editable draft journeys");
assert.equal(verifiedByUser.length,131,"Preserve 18 baseline plus 113 newly transcribed journeys");
assert.equal(verifiedByUser.filter(t=>t.route_id==="zeralda-agha").length,14,"All original Zeralda–Agha timetable trips preserved");
assert.equal(verifiedByUser.filter(t=>["alger-thenia","thenia-alger"].includes(t.route_id)&&["27","33","22","28"].includes(t.train_number)).length,4,"Preserve the four baseline Alger–Thenia gallery trains despite later timetable additions");
assert(stations.some(s=>s.id==="rouiba"),"Rouiba station is indexed");
assert.equal(new Set(stations.map(s=>s.id)).size,stations.length,"Station IDs must be unique");
assert(stations.some(s=>s.id==="les_ateliers"),"Canonical station IDs used after geodata update");
assert(routes.some(r=>r.id==="alger-thenia"&&r.stops.includes("rouiba")),"Rouiba should be visible in eastbound route");
assert(routes.some(r=>r.id==="thenia-alger"&&r.stops.includes("rouiba")),"Rouiba should be visible in westbound route");
assert.equal(stations.length,169,"Official PDF station inventory should include 169 distinct records");
assert.equal(stations.filter(s=>s.geo_verified===true).length,116,"All original protected Google Maps station coordinates preserved");
assert.equal(routes.length,34,"34 documented direction-aware routes including short turns and legacy aliases");
for(const [routeId,n] of [["alger-airport",14],["airport-agha",14],["alger-zeralda",14],["alger-affroun",18],["alger-oued-aissi",3],["thenia-oued-aissi",8],["oued-aissi-alger",3],["oued-aissi-thenia",8],["zeralda-thenia",2],["thenia-zeralda",2],["zeralda-reghaia",1],["reghaia-zeralda",1],["alger-thenia",14],["thenia-alger",13],["alger-reghaia",1],["reghaia-alger",1]]){
 assert.equal(verifiedByUser.filter(t=>t.route_id===routeId).length,n,routeId+" official image-transcribed trains");
}
const weekday1051=available.find(t=>t.route_id==="alger-affroun"&&t.train_number==="1051"&&t.service_id==="except_friday");
const friday1051=available.find(t=>t.route_id==="alger-affroun"&&t.train_number==="1051"&&t.service_id==="friday_only");
assert(weekday1051&&friday1051,"Separate weekday and Friday-only train 1051 columns");
assert.equal(engine.runsOn(weekday1051,"2026-09-25",calendars,exceptions,holidays),false);
assert.equal(engine.runsOn(friday1051,"2026-09-25",calendars,exceptions,holidays),true);
assert.equal(engine.runsOn(friday1051,"2026-09-24",calendars,exceptions,holidays),false);
const b114=available.find(t=>t.route_id==="oued-aissi-alger"&&t.train_number==="B114");
assert(b114&&b114.stop_times.some(x=>x.station_id==="thenia"&&x.arrival==="06:21"&&x.departure==="06:23"),"SNTF image differentiates Thenia arrival/departure");
assert(available.some(t=>t.route_id==="thenia-zeralda"&&t.train_number==="B100/505"));
assert(available.some(t=>t.route_id==="reghaia-zeralda"&&t.train_number==="B104/509"));
assert.equal(engine.recordsAtStation(available,"airport","departure","2026-09-25",config,new Date("2026-09-25T04:00:00Z")).some(e=>e.destination==="agha"),true,"Airport return departures published from photo");
const tr1500=available.find(t=>t.train_number==="1500"),tr1502=available.find(t=>t.train_number==="1502");
assert(tr1500&&tr1502);
assert.equal(engine.runsOn(tr1500,"2026-09-24",calendars,exceptions,holidays),true,"1500 should operate on a Thursday");
assert.equal(engine.runsOn(tr1500,"2026-09-25",calendars,exceptions,holidays),false,"1500 should not operate on Friday");
assert.equal(engine.runsOn(tr1502,"2026-09-25",calendars,exceptions,holidays),true,"1502 should operate Friday");
assert.equal(engine.runsOn(tr1500,"2026-09-18",calendars,exceptions,holidays),false,"Image timetable not before effective date");
const fridayOnly=drafts.find(t=>t.service_id==="friday_holiday");
const excludingHoliday=drafts.find(t=>t.service_id==="weekday_not_friday");
assert(fridayOnly&&excludingHoliday);
assert.equal(engine.runsOn(fridayOnly,"2026-09-24",calendars,exceptions,["2026-09-24"]),true,"Holiday-only service should operate on listed holiday");
assert.equal(engine.runsOn(excludingHoliday,"2026-09-24",calendars,exceptions,["2026-09-24"]),false,"Excluding service should not operate on listed holiday");
const beforeDeparture=new Date("2026-09-24T05:20:00Z"); // 06:20 in Algeria.
const fromZeralda=engine.recordsAtStation(available,"zeralda","departure","2026-09-24",config,beforeDeparture);
assert(fromZeralda.some(e=>e.trip.train_number==="1502"&&engine.formatTime(e.stop.departure)==="06:55"),"Upcoming outbound departures should be listed");
const atAgha=engine.recordsAtStation(available,"agha","arrival","2026-09-24",config,beforeDeparture);
assert(atAgha.some(e=>e.trip.train_number==="1500"&&engine.formatTime(e.stop.arrival)==="07:01"),"Arrivals at terminal should be listed");
assert(!engine.recordsAtStation(available,"agha","departure","2026-09-24",config,beforeDeparture).some(e=>e.trip.train_number==="1500"),"No false departure at terminating station");
const mid=engine.recordsAtStation(available,"birtouta","departure","2026-09-24",config,beforeDeparture);
assert(mid.some(e=>e.trip.train_number==="1502"&&e.destination==="agha"&&e.previous==="tessala_el_merdja"),"Intermediate station events must retain direction and previous stop");
const rouibaOutbound=engine.recordsAtStation(available,"rouiba","departure","2026-09-24",config,new Date("2026-09-24T05:15:00Z"));
assert(rouibaOutbound.some(e=>e.trip.train_number==="27"&&e.destination==="thenia"&&e.stop.departure==="06:57"),"Rouiba eastbound train 27 transcribed from image");
assert(rouibaOutbound.some(e=>e.trip.train_number==="22"&&e.destination==="alger"&&e.stop.departure==="06:26"),"Rouiba westbound train 22 transcribed from reverse image");
assert(rouibaOutbound.some(e=>e.trip.train_number==="33"&&e.destination==="thenia"&&e.stop.departure==="08:05"),"Rouiba daily eastbound 33");
assert(rouibaOutbound.some(e=>e.trip.train_number==="28"&&e.destination==="alger"&&e.stop.departure==="07:12"),"Rouiba daily westbound 28");
assert(!engine.runsOn(available.find(t=>t.trip_id==="gallery-alger-thenia-27-2026-09-19"),"2026-09-25",calendars,exceptions,holidays),"Image train 27 does not operate on Friday");
assert(engine.runsOn(available.find(t=>t.trip_id==="gallery-thenia-alger-28-2026-09-19"),"2026-09-25",calendars,exceptions,holidays),"Image train 28 operates daily");
const train27=available.find(t=>t.trip_id==="gallery-alger-thenia-27-2026-09-19");
assert(!train27.stop_times.some(s=>["rouiba_snvi","reghaia_zi"].includes(s.station_id)),"Dashes in image mean no documented stop for train 27");
const draftsFromRouiba=engine.recordsAtStation(drafts,"rouiba","departure","2026-09-24",config,beforeDeparture);
assert.equal(draftsFromRouiba.length,0,"A draft intermediate stop without time must not appear on departures");
const night=drafts.find(t=>t.route_id==="oran-bechar");
assert(night,"Need one overnight draft for rollover check");
const dawn=new Date("2026-09-24T04:00:00Z"); // 05:00 in Algeria.
const arrivals=engine.recordsAtStation([night],"bechar","arrival","2026-09-24",config,dawn);
assert(arrivals.some(e=>e.serviceDate==="2026-09-23"&&e.remaining===2400),"Yesterday's overnight service arrives this morning");
assert.equal(engine.countdown(3661),"01:01:01");
console.log("DZ Rail board tests PASS: 131 transcribed services, 169 stations, 34 routes, both-direction airport and eastern commuter timetables, Friday-only schedules, distinct arrival/departure, source isolation, overnight rollover and countdown.");
